name: Versatile PyInstaller
author: '@sayyid5416'
description: GitHub Action to package python scripts into executables
branding: 
  icon: hard-drive
  color: blue


inputs:
  spec:
    description: file path of .spec file
    required: true
    default: ''
  requirements:
    description: file path of requirements.txt file
    required: False
    default: ''
  python_ver:
    description: specific python version
    required: False
    default: '3.10'
  exe_path:
    description: file path where executable will be saved
    required: False
    default: './dist'
  upload_exe_with_name:
    description: Name of exe to be uploaded, if passed
    required: False
    default: ''

outputs:
  executable_path:
    description: path where generated executable files are stored
    value: ${{ inputs.exe_path }}
  is_uploaded:
    description: true/<anything>, if packaged executable is uploaded
    value: ${{ steps.exe_uploading.uploaded }}



runs:
  using: 'composite'
  steps:

    - name: Checks for required inputs
      if: inputs.spec == '' || !endsWith(inputs.spec, '.spec')
      shell: bash
      run: |
        echo "::error::Missing or Wrong 'spec' in inputs" 
        exit 1

    - name: Checkout
      uses: actions/checkout@main

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_ver }}
    
    - name: Installing/Upgrading python dev tools
      run: python -m pip install pip wheel setuptools
      shell: bash
    
    - name: Install dependencies
      if: inputs.requirements != ''
      run: python -m pip install -r "${{ inputs.requirements }}"
      shell: bash

    - name: Install pyinstaller
      run: pip install pyinstaller
      shell: bash
    
    - name: Creating the executable
      run: |
        pyinstaller --clean -y --dist ${{ inputs.exe_path }} "${{ inputs.spec }}"
        echo "✔️ Executable created successfully at _'${{ inputs.exe_path }}'_" >> $GITHUB_STEP_SUMMARY
      shell: bash
    
    - name: Uploading executable
      if: inputs.upload_exe_with_name != ''
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.upload_exe_with_name }}
        path: ${{ inputs.exe_path }}
    
    - name: Uploading executable (Part-2)
      id: exe_uploading
      if: inputs.upload_exe_with_name != ''
      run: |
        echo "✔️ Executable **_(${{ inputs.upload_exe_with_name }})_** uploaded successfully" >> $GITHUB_STEP_SUMMARY
        echo "uploaded='true'" >> $GITHUB_OUTPUTS
      shell: bash